name: Reporting CLI tests workflow

on: [pull_request, push]

jobs:
  run-tests:
    name: Run reporting cli tests 

    strategy:
      matrix:
        opensearch-version: [ "1.3.8", "2.0.0", "2.1.0", "2.2.1", "2.2.1", "2.3.0", "2.4.1", "2.5.0" ]
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Reporting CLI
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Configure sysctl limits
        run: |
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Download and run Opensearch and Dashboard
        run: |
          docker run -d -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" opensearchproject/opensearch:${{ opensearch-version }}
          docker pull opensearchproject/opensearch-dashboards:${{ opensearch-version }}
          docker run -d -it --network="host" opensearchproject/opensearch-dashboards:${{ opensearch-version }}
      
      - name: Check Docker containers
        run: docker ps -a

      - name: Sleep for 400s seconds
        run: sleep 400s
        shell: bash

      - name: Wait for cluster to start
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 1
          max_attempts: 30
          command: curl https://localhost:9200 -ku 'admin:admin'
          retry_wait_seconds: 30

      - name: Add sample data
        run: |
          curl -XPOST -u 'admin:admin' 'http://localhost:5601/api/sample_data/ecommerce' -H 'osd-xsrf:true'
          curl -XPOST -u 'admin:admin' 'http://localhost:5601/api/sample_data/logs' -H 'osd-xsrf:true'  -H 'securitytenant: global'
          curl -XPOST -u 'admin:admin' 'http://localhost:5601/api/sample_data/flights' -H 'osd-xsrf:true'  -H 'securitytenant: admin_tenant'

      - name: Run integration tests
        run: |
          yarn
          yarn test
      
      - name: Clean up container
        if: always()
        run: |
          docker-compose down
